version: '3.8'

services:
  fragments:
    init: true
    build: .
    image: fragments:latest
    container_name: lab5-fragments-1 
    environment:
      - API_URL=${API_URL:-http://localhost:8080}
      - HTPASSWD_FILE=tests/.htpasswd
      - FRAGMENTS_LOG_LEVEL=${FRAGMENTS_LOG_LEVEL:-debug} 
      
      - AWS_COGNITO_POOL_ID=${AWS_COGNITO_POOL_ID}
      - AWS_COGNITO_CLIENT_ID=${AWS_COGNITO_CLIENT_ID}
      - AWS_COGNITO_AUTH_FLOW=${AWS_COGNITO_AUTH_FLOW:-USER_PASSWORD_AUTH}
      - AWS_COGNITO_DOMAIN=${AWS_COGNITO_DOMAIN}
      - AWS_COGNITO_REDIRECT_URI=${AWS_COGNITO_REDIRECT_URI}

      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_S3_ENDPOINT_URL=http://ministack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      
      - AWS_DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
      - AWS_DYNAMODB_TABLE_NAME=${AWS_DYNAMODB_TABLE_NAME:-fragments}
    ports:
      - '8080:8080'
    depends_on:
      - ministack
      - dynamodb-local

  ministack:
    image: ministackorg/ministack:latest
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3
      - DEBUG=1

  # DynamoDB Local
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
    command: ['-jar', 'DynamoDBLocal.jar', '-inMemory']