version: '3.8'

services:
  # Fragments microservice API server
  fragments:
    init: true
    build: .
    environment:
      - API_URL=http://localhost:8080
      - HTPASSWD_FILE=tests/.htpasswd
      - FRAGMENTS_LOG_LEVEL=${FRAGMENTS_LOG_LEVEL:-info}
      
      # Cognito variables
      - AWS_COGNITO_POOL_ID=us-east-1_nOJcadJ1N
      - AWS_COGNITO_CLIENT_ID=24q9oumidh9g96papdh4daicna
      - AWS_COGNITO_AUTH_FLOW=USER_PASSWORD_AUTH
      - AWS_COGNITO_DOMAIN=https://us-east-1nojcadj1n.auth.us-east-1.amazoncognito.com
      - AWS_COGNITO_REDIRECT_URI=http://localhost:1234
      
      # Local MiniStack S3 configuration
      - AWS_REGION=us-east-1
      - AWS_S3_BUCKET_NAME=fragments
      - AWS_S3_ENDPOINT_URL=http://ministack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      
      # DynamoDB local configuration
      - AWS_DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
      - AWS_DYNAMODB_TABLE_NAME=${AWS_DYNAMODB_TABLE_NAME:-fragments}
    ports:
      - '8080:8080'
    depends_on:
      - ministack
      - dynamodb-local

  # MiniStack S3 local emulator service
  ministack:
    image: ministackorg/ministack:latest
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3
      - DEBUG=1

  # DynamoDB Local
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
    command: ['-jar', 'DynamoDBLocal.jar', '-inMemory']