name: CI

on: [push, pull_request]

jobs:
  build-ui:
    name: Build Fragments UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: lab7/fragments-ui

      - name: Build project
        run: npm run build
        working-directory: lab7/fragments-ui

  dockerfile-lint:
    name: Dockerfile Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: lab7/assignment-01/fragments/lab5/Dockerfile