# Create a simple cache called `fragments_cache`, and use `/tmp/nginx_cache`
# on disk and 10 MB of memory to store the cache keys. See:
# https://www.nginx.com/blog/nginx-caching-guide/
proxy_cache_path /tmp/nginx_cache keys_zone=fragments_cache:10m;  

# Define our server
server {
    # Listen on localhost:80
    server_name localhost;
    listen      80;

    # All requests to / get handled here
    location / {
        # Put a cache in front of our API server
        proxy_cache             fragments_cache;
        # Proxy everything else to our fragment API server's container, port 8080
        proxy_pass              http://fragments:8080;
    }
}
