services:
  dynamodb:
    container_name: 'dynamodb'
    image: amazon/dynamodb-local
    command: ['-jar', 'DynamoDBLocal.jar', '-inMemory']

  mqtt-temps:
    container_name: 'mqtt-temps'
    init: true
    build: .
    environment:
      - MQTT_URL=mqtt://mqtt-broker:1883
      - DYNAMODB_ENDPOINT_URL=http://dynamodb:8000
    ports:
      - "3000:3000"

  mqtt-broker:
    container_name: 'mqtt-broker'
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  device-1:
    container_name: 'device-1'
    init: true
    build: ./device-mock
    environment:
      - MQTT_URL=mqtt://mqtt-broker:1883
      - DEVICE_ID=7ts47y

  device-2:
    container_name: 'device-2'
    init: true
    build: ./device-mock
    environment:
      - MQTT_URL=mqtt://mqtt-broker:1883
      - DEVICE_ID=pytqry

  device-3:
    container_name: 'device-3'
    init: true
    build: ./device-mock
    environment:
      - MQTT_URL=mqtt://mqtt-broker:1883
      - DEVICE_ID=jbsbzd
