AWSTemplateFormatVersion: 2010-09-09

Description: Our first CloudFormation S3 Bucket

Parameters:
  MyBucketName:
    Type: String
    Description: My S3 Bucket Name

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${MyBucketName}

Outputs:
  BucketName:
    Value: !Ref MyS3Bucket
